name: update-demo-daily
on:
  schedule:
    - cron: "0 6 * * *"
  push:
    tags:
      - "refresh-github-page"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare-page
        env:
          FEEDS: ${{vars.FEEDS}}
        run: |
          wget -q -O tinyfeed https://github.com/TheBigRoomXXL/tinyfeed/releases/latest/download/tinyfeed_linux_arm64
          chmod +x tinyfeed
          mkdir www
          echo $FEEDS | ./tinyfeed > ./www/index.html
          cp www/index.html www/404.html

      - name: upload-page
        uses: actions/upload-pages-artifact@56afc60
        with:
          path: www/

  deploy:
    needs: build
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy-to-github-pages
        id: deployment
        uses: actions/deploy-pages@d6db901
