name: build-and-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: setup-repos
        uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v4

      - name: verify-dependencies
        run: go mod verify

      - name: build
        run: go build

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "tinyfeed"
