name: build-and-release
on:
  push:
    tags:
      - "*.*.*"
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: setup-repos
        uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v4

      - name: verify-dependencies
        run: go mod verify

      - name: build
        run: go build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: tinyfeed
          draft: false
          prerelease: false
