name: build-and-release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: setup-repos
        uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v4

      - name: cross-platform-build
        run: |
          mkdir ./builds/
          env GOARCH=arm64
          env GOOS=linux go build -o ./builds/tinyfeed_linux_arm64
          env GOOS=freebsd go build -o ./builds/tinyfeed_freebsd_arm64
          env GOOS=darwin go build -o ./builds/tinyfeed_darwin_arm64
          env GOOS=windows go build -o ./builds/tinyfeed_windows_arm64
          env GOARCH=amd64
          env GOOS=linux go build -o ./builds/tinyfeed_linux_amd64
          env GOOS=freebsd go build -o ./builds/tinyfeed_freebsd_amd64
          env GOOS=darwin go build -o ./builds/tinyfeed_darwin_amd64
          env GOOS=windows go build -o ./builds/tinyfeed_windows_amd64

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./builds/*"
